spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:test
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 336298008304-kjbn6on2tdehjraoeplrb17gbqnvl4f0.apps.googleusercontent.com
            clientSecret: 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
            scope:
              - email
              - profile